import Cocoa

// The TextKit half of code folding: an NSLayoutManager that lays out a set of
// character ranges as nothing at all.
//
// TextKit 1 has no "hidden text" API, but it has the two hooks needed to build
// one, and this is the long-standing recipe for it:
//
//   1. setGlyphs — mark every glyph whose character is inside a hidden range as
//      `.null`, so it generates no glyph and takes no width.
//   2. setLineFragmentRect — a line whose characters are *entirely* hidden still
//      gets a line fragment (paragraphs survive glyph suppression), so it would
//      lay out as a blank row. Flattening the fragment to zero height is what
//      actually makes the block disappear rather than turn into whitespace.
//
// Everything else in the viewer — the gutter's line-fragment walk, the minimap,
// find, blame — reads positions back through the layout manager, so all of it
// follows folding for free without knowing folding exists.
final class FoldingLayoutManager: NSLayoutManager {

    // Character ranges to hide, disjoint and ascending. Set by
    // FileViewerPane+Folding; assigning re-runs glyph generation and layout for
    // the whole document, which is why the setter is not called per keystroke.
    var hiddenRanges: [NSRange] = [] {
        didSet {
            guard hiddenRanges != oldValue else { return }
            let length = textStorage?.length ?? 0
            guard length > 0 else { return }
            let all = NSRange(location: 0, length: length)
            invalidateGlyphs(forCharacterRange: all, changeInLength: 0, actualCharacterRange: nil)
            invalidateLayout(forCharacterRange: all, actualCharacterRange: nil)
        }
    }

    private func isHidden(_ characterIndex: Int) -> Bool {
        // Ranges are ascending and disjoint; files with hundreds of folds are
        // rare enough that a linear scan beats the bookkeeping of a binary one.
        for range in hiddenRanges {
            if characterIndex < range.location { return false }
            if characterIndex < NSMaxRange(range) { return true }
        }
        return false
    }

    override func setGlyphs(
        _ glyphs: UnsafePointer<CGGlyph>,
        properties: UnsafePointer<NSLayoutManager.GlyphProperty>,
        characterIndexes: UnsafePointer<Int>,
        font: NSFont,
        forGlyphRange glyphRange: NSRange
    ) {
        guard !hiddenRanges.isEmpty else {
            super.setGlyphs(glyphs, properties: properties, characterIndexes: characterIndexes,
                            font: font, forGlyphRange: glyphRange)
            return
        }

        var updated = Array(UnsafeBufferPointer(start: properties, count: glyphRange.length))
        var changed = false
        for i in 0..<glyphRange.length where isHidden(characterIndexes[i]) {
            updated[i].insert(.null)
            changed = true
        }
        guard changed else {
            super.setGlyphs(glyphs, properties: properties, characterIndexes: characterIndexes,
                            font: font, forGlyphRange: glyphRange)
            return
        }
        updated.withUnsafeBufferPointer { buffer in
            super.setGlyphs(glyphs, properties: buffer.baseAddress!, characterIndexes: characterIndexes,
                            font: font, forGlyphRange: glyphRange)
        }
    }

    override func setLineFragmentRect(
        _ fragmentRect: NSRect,
        forGlyphRange glyphRange: NSRange,
        usedRect: NSRect
    ) {
        guard !hiddenRanges.isEmpty, glyphRange.length > 0 else {
            super.setLineFragmentRect(fragmentRect, forGlyphRange: glyphRange, usedRect: usedRect)
            return
        }

        // Glyphs are already generated by the time fragments are placed, so
        // mapping back to characters here is safe and doesn't re-enter layout.
        let first = characterIndexForGlyph(at: glyphRange.location)
        let last = characterIndexForGlyph(at: NSMaxRange(glyphRange) - 1)
        guard isHidden(first), isHidden(last) else {
            super.setLineFragmentRect(fragmentRect, forGlyphRange: glyphRange, usedRect: usedRect)
            return
        }

        var flatFragment = fragmentRect
        var flatUsed = usedRect
        flatFragment.size.height = 0
        flatUsed.size.height = 0
        super.setLineFragmentRect(flatFragment, forGlyphRange: glyphRange, usedRect: flatUsed)
    }
}
